export const NEW_BIRTH_REQUEST = "births.NEW_BIRTH_REQUEST"
export const NEW_BIRTH_SUCCESS = "births.NEW_BIRTH_SUCCESS"
export const NEW_BIRTH_ERROR = "births.NEW_BIRTH_ERROR"

export const BIRTH_LIST_REQUEST = "births.BIRTH_LIST_REQUEST"
export const BIRTH_LIST_SUCCESS = "births.BIRTH_LIST_SUCCESS"
export const BIRTH_LIST_ERROR = "births.BIRTH_LIST_ERROR"

export const BIRTH_DETAILS_REQUEST = "births.BIRTH_DETAILS_REQUEST"
export const BIRTH_DETAILS_SUCCESS = "births.BIRTH_DETAILS_SUCCESS"
export const BIRTH_DETAILS_ERROR = "births.BIRTH_DETAILS_ERROR"

export const VACCINE_LIST_REQUEST = "births.VACCINE_LIST_REQUEST"
export const VACCINE_LIST_SUCCESS = "births.VACCINE_LIST_SUCCESS"
export const VACCINE_LIST_ERROR = "births.VACCINE_LIST_ERROR"

